"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

    1. $ rm -rf build dist
    2. $ python3 example/setup.py py2app -A
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {'iconfile': 'icon/icon.png'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
